name: world_cue
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2



dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.3.1
  flutter_svg: ^2.2.1
  shared_preferences: ^2.5.3
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  delightful_toast: ^1.1.0
  lottie: ^3.3.2
  connectivity_plus: ^7.0.0
  get: ^4.7.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  firebase_core: ^4.2.0
  google_sign_in: ^6.2.1
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  http: ^1.5.0
  url_launcher: ^6.3.2
  photo_view: ^0.15.0
  firebase_messaging: ^16.0.1
  flutter_local_notifications: ^19.4.1
  firebase_crashlytics: ^5.0.4
  permission_handler: ^12.0.1
  flutter_dotenv: ^6.0.0


dev_dependencies:
  change_app_package_name: ^1.5.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  intl_utils: ^2.8.12
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.png
  android_12:
    color: "#ffffff"
    image: assets/splash.png
    web: false

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:

  uses-material-design: true

  # project assets
  assets:
    - assets/
    - .env

flutter_intl:
  enabled: true
  localizely:
    project_id: a712bfcf-e4c2-440b-b89d-2a0f191c57ae
    api_token: 85f14c9f887846e4813d899956a03482678282f410fd4ae49bc694a8641bbe87
